### ISSUE TITLE
SMRTLink GUI options for Polished HGAP 4 Assembly need some work

### ISSUE THREAD

**Issue by ben-lerch** [PacificBiosciences/FALCON-pbsmrtpipe#5]
I have made some suggestions to the options I pulled from the GUI on Monday. They fall into 4 categories: looks good, possibly remove, revised, and possibly replace with multiple options. The last category is for options that appear to have multiple relevant parameters and should be broken up for the GUI. The possibly remove category is for options that don't appear relevant for the GUI. These are mostly ones concerning how jobs are managed on the cluster. I'm guessing the user won't have control of that, but I could be wrong. And for the revised category, I put the revised name and description just below the original option.
### looks good
- Min. accuracy
  - Minimum required alignment accuracy (percent)
- Minimum confidence
  - The minimum confidence for a variant call to be output to variants.gff
- Concordant alignment
  - Map subreads of a ZMW to the same genomic location
- Diploid mode (experimental)
  - Enable detection of heterozygous variants (experimental)
- Min. length
  - Minimum required alignment length
- Use CCS
  - Map the ccsSequence to the genome first, then align subreads to the interval that the CCS reads mapped to.
    - useccs: only maps subreads that span the length of the template.
    - useccsall: maps all subreads.
    - useccsdenovo: maps ccs only.
- Minimum coverage
  - The minimum site coverage that must be achieved for variant calls and consensus to be calculated for a site.
- Hit policy
  - Specify a policy for how to treat multiple hit
    - random : selects a random hit.
    - all : selects all hits.
    - allbest : selects all the best score hits.
    - randombest: selects a random hit from all best score hits.
    - leftmost : selects a hit which has the best score and the smallest mapping coordinate in any reference.
    - Default value is randombest.
### possibly remove
- Option input_fofn
- Option input_fofn description
- Option pa_concurrent_jobs
- Option pa_concurrent_jobs description
- Option input_type
- Option input_type description
- Option sge_option_da
- Option sge_option_da description
- Option sge_option_pla
- Option sge_option_pla description
- Option jobqueue
- Option jobqueue description
- Option sge_option_cns
- Option sge_option_cns description
- Option sge_option_fc
- Option sge_option_fc description
- Option job_type
- Option job_type description
- Option sge_option_la
- Option sge_option_la description
- Option sge_option_pda
- Option sge_option_pda description
- Option ovlp_concurrent_jobs
- Option ovlp_concurrent_jobs description
### revised
- Option length_cutoff_pr
- Option length_cutoff_pr description
  - Read length cutoff (alignment stage)
  - Specifies the minimum read length used during the assembly stage
- Option overlap_filtering_setting
- Option overlap_filtering_setting description
  - Max overlap reported
  - Controls the maximum overlap reported for each read during overlap filtering.
- Option ovlp_DBsplit_option
- Option ovlp_DBsplit_option description
  - Dataset Chunking (Overlapping detection of the error corrected reads)
  - Determines how to break the database into chunks that will be processed in parallel in the overlapping detection of the error corrected reads stage. See for details:
    - https://dazzlerblog.wordpress.com/2014/06/01/the-dazzler-db/#DBsplit
- Option pa_DBsplit_option
- Option pa_DBsplit_option description
  - Dataset Chunking (Pre-assembly and error correction) 
  - Determines how to break the database into chunks that will be processed in parallel in the pre-assembly and error correction stage. See for details:
    - https://dazzlerblog.wordpress.com/2014/06/01/the-dazzler-db/#DBsplit
- Algorithm
  - Specify whether to use Quiver or Plurality 
- Algorithm options
  - List of space-separated arguments passed to BLASR (etc.)
- BLASR options
  - List of space-separated arguments passed to BLASR. See BLASR documentation for full list of options. Basic options are: -useQuality -minMatch -bestn -minPctSimilarity
  - Then link to this somewhere:
    -useQuality
               Use substitution/insertion/deletion/merge quality values to score gap and
               mismatch penalties in pairwise alignments.  Because the insertion and deletion
               rates are much higher than substitution, this will make many alignments
               favor an insertion/deletion over a substitution.  Naive consensus calling methods
               will then often miss substitution polymorphisms. This option should be
               used when calling consensus using the Quiver method.  Furthermore, when
               not using quality values to score alignments, there will be a lower consensus
               accuracy in homopolymer regions.
    
    -minMatch
             Minimum seed length.  Higher minMatch will speed up alignment, but decrease sensitivity.
    
    -bestn
             Report the top 'n' alignments.
    
    -minPctSimilarity
             Report alignments only if their percentage similarity is greater than minPctSimilarity.
- Option length_cutoff description
  - Read length cutoff (error correction stage)
  - Specifies the minimum read length used during the error correction stage
### possibly replace with multiple options
- Option pa_HPCdaligner_option
- Option pa_HPCdaligner_option description
- Option falcon_sense_option
- Option falcon_sense_option description
- Option ovlp_HPCdaligner_option
- Option ovlp_HPCdaligner_option description

**Comment by pb-cdunn** [comment]
Oh, here is an update: JimD has requested simplified settings. We plan to have basically "genome size" and "number of chunks". We'll try to generate some reasonable settings from that.

**Comment by ben-lerch** [comment]
OK, and I noticed I didn't comment on the Algorithms Options option. Here is my suggestion:

#revised
Algorithm options
List of space-separated arguments passed to BLASR (etc.)
BLASR options
List of space-separated arguments passed to BLASR. See BLASR documentation for full list of options. Basic options are: -useQuality -minMatch -bestn -minPctSimilarity

Then link to this somewhere:
-useQuality
               Use substitution/insertion/deletion/merge quality values to score gap and
               mismatch penalties in pairwise alignments.  Because the insertion and deletion
               rates are much higher than substitution, this will make many alignments
               favor an insertion/deletion over a substitution.  Naive consensus calling methods
               will then often miss substitution polymorphisms. This option should be
               used when calling consensus using the Quiver method.  Furthermore, when
               not using quality values to score alignments, there will be a lower consensus
               accuracy in homopolymer regions.

 -minMatch
               Minimum seed length.  Higher minMatch will speed up alignment, but decrease sensitivity.

 -bestn
               Report the top 'n' alignments.

 -minPctSimilarity
               Report alignments only if their percentage similarity is greater than minPctSimilarity.

**Comment by pb-cdunn** [comment]
I've been updating the markdown in your comments. It's worth learning:
* https://help.github.com/articles/markdown-basics/
* https://help.github.com/articles/github-flavored-markdown/

**Comment by ben-lerch** [comment]
oh i see. yes i'll use that formatting in the future.

**Comment by pb-cdunn** [comment]
Here is what I'm working on now:

* "name": "Genome length (base pairs)",
  * "description": "Approx. number of base pairs expected in the genome."
* "name": "Cores Max.",
  * "description": "Maximum number of cores to use simultaneously across the network. For any given Task, this setting might further reduce the number of 'chunks', beneather the global maximum. Note that a Task can use multiple cores in 2 ways: processes and threads. You can assume that our Tasks honestly report what they expect to consume."
* "name": "FALCON cfg overrides",
  * "description": "This is intended to allow support engineers to overrides the config which we will generate from other options. It is a semicolon-separated list of key=val pairs. Newlines are allowed by ignored. For more details on the available options, see https://github.com/PacificBiosciences/FALCON/wiki/Manual"

There are some typos -- hard to spot until I actually see this in the GUI. If we have time, we can fix those before the release.

Anyway, "Falcon cfg overrides" will be empty by default, and hopefully it will never be needed. It's for all the complicated stuff.

"Genome length" will select a bunch of appropriate values magically for the hidden advanced options. Those values will not even be displayed in the GUI. You'd have to go to the actual log-files to see them. I'd like to see them in the GUI logs, but I'll have to negotiate with MPK on that.

"Cores Max." is an extra constraint beyond just max_nchunks. It will look at each task's "nproc" potentially to create different numbers of chunks for different tasks. It's experimental and actually not implemented yet.
